<?php

class Grandpa
{


    public $body = 'Нормальное';

    private $nose = 'Кривой';

    public function eat($calories)
    {
        if ($calories > 500) {
            $this->body = 'Толстый';
        } else {
            $this->body = 'Худой';
        }
    }

    protected function showGranpaNose()
    {
        return $this->nose;
    }
}

class Father extends Grandpa
{
    protected $hair = 'Русые';

    public function showGranpaNose()
    {
        $nose = parent::showGranpaNose(); // TODO: Change the autogenerated stub
        $nose .= ' не очень';
        echo $nose . '<br>';
    }

}

$masha = new Father();

$ivan = new Father();

$masha->showGranpaNose();


$masha = new Father();

$ivan = new Father();

$petya = new Father();

echo 'T Маши - ' . $masha->body . '<br>';
echo 'T Ивана - ' . $ivan->body . '<br>';

$masha->eat(200);
$ivan->eat(2000);

$masha->hair = 'Белые';
